steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
- id: 'tf init'
  name: 'hashicorp/terraform:0.13.1'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      terraform init
- id: 'tf plan'
  name: 'hashicorp/terraform:0.13.1'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      terraform plan
- id: 'tf apply'
  name: 'hashicorp/terraform:0.13.1'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      terraform apply -auto-approve